### PR TITLE
[ISSUE #198] support nameserver run on cgroup v2

### LINKED ISSUE #188: rocketmq 5. x 构建镜像，使用operator启动集群时，namesrv无法启动
**BUG REPORT**

1. Please describe the issue you observed:
我使用的是rocketmq5.x的版本，用的是示例的脚本构建的broker和namesrv的镜像，然后使用官方的提供的example启动一个集群，但是namesrv一直启动不起来，namesrv中的报错日志如下，broker主从节点启动都没有问题。5.0.x的版本和5.1.x的版本我都试过了，都是namesrv这个地方报错，想问一下这个是什么情况？

// namesrv日志报错
cat: can't open '/sys/fs/cgroup/memory/memory.limit_in_bytes': No such file or directory
/root/rocketmq/nameserver/bin/runserver.sh: line 58: arithmetic syntax error

// 下面是我的启动集群的配置文件（使用的官方的）
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: default
data:
  # BROKER_MEM sets the broker JVM, if set to "" then Xms = Xmx = max(min(1/2 ram, 1024MB), min(1/4 ram, 8GB))
  BROKER_MEM: " -Xms1g -Xmx1g -Xmn1g "
  broker-common.conf: |
    # brokerClusterName, brokerName, brokerId are automatically generated by the operator and do not set it manually!!!
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    # set brokerRole to ASYNC_MASTER or SYNC_MASTER. DO NOT set to SLAVE because the replica instance will automatically be set!!!
    brokerRole=ASYNC_MASTER

---
apiVersion: rocketmq.apache.org/v1alpha1
kind: Broker
metadata:
  # name of broker cluster
  name: broker
  namespace: default
spec:
  # size is the number of the broker cluster, each broker cluster contains a master broker and [replicaPerGroup] replica brokers.
  size: 1
  # nameServers is the [ip:port] list of name service
  nameServers: ""
  # replicaPerGroup is the number of each broker cluster
  replicaPerGroup: 1
  # brokerImage is the customized docker image repo of the RocketMQ broker
  brokerImage: registry.cn-hangzhou.aliyuncs.com/super-yao/supertest:rocketmq-broker-operator-5.0.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  # resources describes the compute resource requirements and limits
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  # allowRestart defines whether allow pod restart
  allowRestart: true
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: EmptyDir
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/broker
  # scalePodName is [Broker name]-[broker group number]-master-0
  scalePodName: broker-0-master-0
  # env defines custom env, e.g. BROKER_MEM
  env:
    - name: BROKER_MEM
      valueFrom:
        configMapKeyRef:
          name: broker-config
          key: BROKER_MEM
  # volumes defines the broker.conf
  volumes:
    - name: broker-config
      configMap:
        name: broker-config
        items:
          - key: broker-common.conf
            path: broker-common.conf
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: broker-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rocketmq-storage
        resources:
          requests:
            storage: 8Gi
---
apiVersion: rocketmq.apache.org/v1alpha1
kind: NameService
metadata:
  name: name-service
  namespace: default
spec:
  # size is the the name service instance number of the name service cluster
  size: 1
  # nameServiceImage is the customized docker image repo of the RocketMQ name service
  nameServiceImage: registry.cn-hangzhou.aliyuncs.com/super-yao/supertest:rocketmq-namesrv-operator-5.0.0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  # hostNetwork can be true or false
  hostNetwork: true
  #  Set DNS policy for the pod.
  #  Defaults to "ClusterFirst".
  #  Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
  #  DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
  #  To have DNS options set along with hostNetwork, you have to specify DNS policy
  #  explicitly to 'ClusterFirstWithHostNet'.
  dnsPolicy: ClusterFirstWithHostNet
  # resources describes the compute resource requirements and limits
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: EmptyDir
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/nameserver
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: namesrv-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rocketmq-storage
        resources:
          requests:
            storage: 1Gi

### LINKED ISSUE #198: Can not run nameserver on cgroup v2
**BUG REPORT**

**1. Please describe the issue you observed:**
When run nameserver on host which use cgroup v2, the nameserver exited with error:
```
cat: can't open '/sys/fs/cgroup/memory/memory.limit_in_bytes': No such file or directory
/root/rocketmq/nameserver/bin/runserver.sh: line 58: arithmetic syntax error
```

**2. Please tell us about your environment:**
截屏2023-11-23 15 15 32
The above picture show the host use cgroup v2.

**3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):**
We should enhance these code:
https://github.com/apache/rocketmq-operator/blob/a8665716c8028741ec106814798e39fe07e6dcaa/images/namesrv/alpine/runserver-customize.sh#L57-L66

### PR DESCRIPTION
**Pull request by drivebyer**
## What is the purpose of the change

support #198 

## Brief changelog

Support nameserver run on cgroup v2.

## Verifying this change

XXXX

**Please go through this checklist to help us incorporate your contribution quickly and easily.**

Notice: `It would be helpful if you could finish the following checklist (the last one is not necessary) before request the community to review your PR`.

- [ ] Make sure there is a [Github issue](https://github.com/apache/rocketmq-operator/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check RBAC rights for Kubernetes roles.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. 
- [ ] Run `make docker-build` to build docker image for operator, try your changes from Pod inside your Kubernetes cluster, **not just locally**. Also provide screenshots to show that the RocketMQ cluster is healthy after the changes. 
- [ ] Before committing your changes, remember to run `make manifests` to make sure the CRD files are updated. 
- [ ] Update documentation if necessary.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by drivebyer** [comment]
PTAL @caigy

File: images/namesrv/alpine/runserver-customize.sh [hunk 1]
```diff
@@ -55,12 +55,27 @@ calculate_heap_sizes()
...
             fi
+
             system_cpu_cores=`egrep -c 'processor([[:space:]]+):.*' /proc/cpuinfo`
-            system_cpu_cores_in_docker=$(($(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)))
+            if [ -f /sys/fs/cgroup/cpu/cpu.cfs_quota_us ]; then
+                system_cpu_cores_in_docker=$(($(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)))
+            elif [ -f /sys/fs/cgroup/cpu.max ]; then
+                QUOTA=$(cut -d ' ' -f 1 /sys/fs/cgroup/cpu.max)
+                PERIOD=$(cut -d ' ' -f 2 /sys/fs/cgroup/cpu.max)
+                system_cpu_cores_in_docker=$(($QUOTA/$PERIOD))
```
Comment (caigy) [inline images/namesrv/alpine/runserver-customize.sh:75]: It seems that 'QUOTA' may be 'max' instead of number? Pls refer [this](https://github.com/opencontainers/runc/issues/2243).

**Review by caigy — CHANGES_REQUESTED** [review]

File: images/namesrv/alpine/runserver-customize.sh (hunk 1 above)
Comment (drivebyer) [reply images/namesrv/alpine/runserver-customize.sh:75]: yes, it maybe return number or 'max' according to https://github.com/opencontainers/runc/issues/2243

I would adapt it.

Comment (drivebyer) [reply images/namesrv/alpine/runserver-customize.sh]: fixed in https://github.com/apache/rocketmq-operator/pull/199/commits/3ff662ff932d57f38ea27cb56b888665ed8cb132

**Review by caigy — APPROVED** [review]

**Review by RockteMQ-AI — APPROVED** [review]
LGTM. Adds cgroup v2 support for NameServer heap/CPU calculation. Properly handles both cgroup v1 (`memory.limit_in_bytes`, `cpu.cfs_quota_us`) and v2 (`memory.max`, `cpu.max`) with fallback and error messages. Also correctly handles `max` quota (no limit) in cgroup v2.

---
*Automated review by github-manager*
